# Generated by Django 4.2.1 on 2023-05-25 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('VoteXApi', '0001_initial'),
    ]

    operations = [
    ]
