# Generated by Django 4.2.1 on 2023-06-04 13:53

import datetime
from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('VoteXApi', '0002_auto_20230525_1700'),
    ]

    operations = [
        migrations.CreateModel(
            name='Election',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('votes_per_voter', models.IntegerField()),
                ('retractable_votes', models.BooleanField(default=False)),
                ('anonymous', models.BooleanField(default=True)),
                ('start_of_voting', models.DateTimeField(auto_now_add=True)),
                ('end_of_voting', models.DateTimeField(default=datetime.datetime(2023, 6, 5, 16, 53, 1, 183641))),
                ('organizations', models.CharField(choices=[('SOFTSERVE', 'softserve'), ('GOOGLE', 'google'), ('BING', 'bing')], max_length=45)),
                ('regions', multiselectfield.db.fields.MultiSelectField(choices=[('VINNYTSIA', 'vinnytsia'), ('VOLYN', 'volyn'), ('DNIPROPETROVSK', 'dnipropetrovsk'), ('DONETSK', 'donetsk'), ('ZHYTOMYR', 'zhytomyr'), ('ZAKARPATTIA', 'zakarpattia'), ('ZAPORIZHZHIA', 'zaporizhzhia'), ('IVANO_FRANKIVSK', 'ivano-frankivsk'), ('KYIV', 'kyiv'), ('KIROVOHRAD', 'kirovohrad'), ('LUHANSK', 'luhansk'), ('LVIV', 'lviv'), ('MYKOLAIV', 'mykolaiv'), ('ODESA', 'odesa'), ('POLTAVA', 'poltava'), ('RIVNE', 'rivne'), ('SUMY', 'sumy'), ('TERNOPIL', 'ternopil'), ('KHARKIV', 'kharkiv'), ('KHERSON', 'kherson'), ('KHMELNYTSKYI', 'khmelnytskyi'), ('CHERKASY', 'cherkasy'), ('CHERNIVTSI', 'chernivtsi'), ('CHERNIHIV', 'chernihiv')], max_length=45)),
                ('role', models.CharField(choices=[('ADMIN', 'admin'), ('VOTER', 'voter')], max_length=45)),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='name',
            field=models.CharField(default='unknown', max_length=120, unique=True),
        ),
        migrations.AddField(
            model_name='user',
            name='organization',
            field=models.CharField(choices=[('SOFTSERVE', 'softserve'), ('GOOGLE', 'google'), ('BING', 'bing')], max_length=45, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='region',
            field=models.CharField(choices=[('VINNYTSIA', 'vinnytsia'), ('VOLYN', 'volyn'), ('DNIPROPETROVSK', 'dnipropetrovsk'), ('DONETSK', 'donetsk'), ('ZHYTOMYR', 'zhytomyr'), ('ZAKARPATTIA', 'zakarpattia'), ('ZAPORIZHZHIA', 'zaporizhzhia'), ('IVANO_FRANKIVSK', 'ivano-frankivsk'), ('KYIV', 'kyiv'), ('KIROVOHRAD', 'kirovohrad'), ('LUHANSK', 'luhansk'), ('LVIV', 'lviv'), ('MYKOLAIV', 'mykolaiv'), ('ODESA', 'odesa'), ('POLTAVA', 'poltava'), ('RIVNE', 'rivne'), ('SUMY', 'sumy'), ('TERNOPIL', 'ternopil'), ('KHARKIV', 'kharkiv'), ('KHERSON', 'kherson'), ('KHMELNYTSKYI', 'khmelnytskyi'), ('CHERKASY', 'cherkasy'), ('CHERNIVTSI', 'chernivtsi'), ('CHERNIHIV', 'chernihiv')], max_length=45, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'admin'), ('VOTER', 'voter')], max_length=45, null=True),
        ),
    ]
