# Generated by Django 4.2.1 on 2023-06-04 13:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VoteXApi', '0003_election_user_name_user_organization_user_region_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='election',
            name='end_of_voting',
            field=models.DateTimeField(default=datetime.datetime(2023, 6, 5, 16, 53, 18, 232779)),
        ),
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(max_length=120, null=True, unique=True),
        ),
    ]
