# Generated by Django 4.2.1 on 2023-06-05 08:42

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('VoteXApi', '0004_alter_election_end_of_voting_alter_user_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='election',
            name='end_of_voting',
            field=models.DateTimeField(default=datetime.datetime(2023, 6, 6, 11, 42, 36, 836470)),
        ),
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('number_of_votes', models.IntegerField()),
                ('election', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='VoteXApi.election')),
            ],
        ),
    ]
