# Generated by Django 4.2.1 on 2023-06-05 12:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VoteXApi', '0006_customuser_delete_user_remove_election_role_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='register_date',
        ),
        migrations.AlterField(
            model_name='election',
            name='end_of_voting',
            field=models.DateTimeField(default=datetime.datetime(2023, 6, 6, 15, 58, 16, 952182)),
        ),
    ]
